//
// Exercise for future, see Princeton Algorithms I, Queues
//

#ifndef ALGORITHMSANDDATASTRUCTURES_RESIZINGARRAYQUEUE_H
#define ALGORITHMSANDDATASTRUCTURES_RESIZINGARRAYQUEUE_H

#endif //ALGORITHMSANDDATASTRUCTURES_RESIZINGARRAYQUEUE_H
